### PR TITLE
Minor changes for priors & adding prerequisite

### PR DESCRIPTION
**Pull request by thomasckng**
Consistent parameter ordering. Zenith always comes before azimuth.

### CODE REVIEW

**Comment by thomasckng** [comment]
Added `jaxtyping` as prerequisite. Older versions do not support `typechecker` argument.

**Comment by thomasckng** [comment]
Added some more prerequisites.

**Comment by thomasckng** [comment]
Use `SingleEventRun` object `trigger_time` and `ifos` directly when `EarthFrame` prior is called via `SingleEventPERunManager`.

**Comment by thomasckng** [comment]
Consistent data type for `Sphere` prior `__init__` input

**Review by kazewong — APPROVED** [review]

**Pull request merged**
