### PR TITLE
Update initial position sampling in maximize_likelihood

### PR DESCRIPTION
**Pull request by thomasckng**
Use the same code in #152 for `maximize_likelihood`.

### CODE REVIEW

**Comment by thomasckng** [comment]
@kazewong Other parts of this function require changes as well. I am not sure how to do that, do you mind taking a look later?

**Comment by kazewong** [comment]
I am not sure what you are trying to do here. The original PR has already been merged.

**Comment by thomasckng** [comment]
The function I changed is in `likelihood.py`. It has the same code structure as the code you merged in #152. Maybe I can change the base to `jim_dev`. It might be more obvious.

**Comment by thomasckng** [comment]
The loops before and after the code I modified still need some work.

**Pull request closed without merging**
